[build]
  publish = "."  # Thư mục build (gốc)
  command = "npm run build"  # Nếu dùng build tool như Vite/Next/React

# --- 🔁 REDIRECTS & CANONICAL FIX ---
[[redirects]]
  from = "http://rubywings.vn/*"
  to = "https://www.rubywings.vn/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.rubywings.vn/*"
  to = "https://www.rubywings.vn/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://rubywings.vn/*"
  to = "https://www.rubywings.vn/:splat"
  status = 301
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# --- 🛡️ SECURITY HEADERS ---
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=()"
    Content-Security-Policy = "default-src 'self' https:; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' https:; style-src 'self' 'unsafe-inline' https:; connect-src 'self' https:; font-src 'self' https: data:;"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin"

# --- ⚡ PERFORMANCE HEADERS ---
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"

# --- 🤖 SEO & AI INDEXING ---
[[headers]]
  for = "/robots.txt"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/"
  [headers.values]
    Link = '</sitemap.xml>; rel="sitemap", </index.html>; rel="canonical"'
    Accept-CH = "DPR, Viewport-Width, Width"
    Alt-Svc = 'h3=":443"; ma=86400'

